-- EV Match Nepal: sourced Nepal-market catalogue
-- Run upgrade-v3.sql first on an existing project, then run this file.
-- "Needs review" means a field still requires a second-source or brochure check.

insert into public.vehicles
  (id, brand, model, variant, price, battery, range, range_standard, seats, clearance, dc,
   service_cities, service_count, qa, evidence, status, source_url, source_label, image_url, body_type, verified_at)
values
  ('tata-tiago-lr-xt', 'Tata', 'Tiago.ev', 'LR XT', 2749000, 24, 291, 'MIDC', 5, null, null,
   array['Biratnagar','Kathmandu Valley','Pokhara','Bharatpur','Butwal'], 21, 'Incomplete', 7, 'active',
   'https://cars.tatamotors.com.np/utility-vehicles/tiago-ev/price.php', 'Tata Motors Nepal', null, 'City hatchback', '2026-07-27'),
  ('tata-punch-ev', 'Tata', 'Punch.ev', 'Nepal-market variant', 3399000, 25, 315, 'MIDC', 5, 190, 50,
   array['Biratnagar','Kathmandu Valley','Pokhara','Bharatpur','Butwal'], 21, 'Needs review', 6, 'active',
   'https://cars.tatamotors.com.np/utility-vehicles/punch-ev.php', 'Tata Motors Nepal',
   '/vehicles/tata-punch.webp', 'Compact SUV', '2026-07-27'),
  ('mg-comet-executive', 'MG', 'Comet EV', 'Executive', 1875000, 17.3, 230, 'ARAI', 4, null, null,
   array['Kathmandu Valley'], 1, 'Incomplete', 8, 'active',
   'https://mgmotor.com.np/cars/comet', 'MG Motor Nepal',
   '/vehicles/mg-comet.webp', 'Urban EV', '2026-07-27'),
  ('mg-windsor-excite', 'MG', 'Windsor EV', 'Excite', 3975000, 38, 331, 'ARAI', 5, null, 50,
   array['Kathmandu Valley'], 1, 'Incomplete', 8, 'active',
   'https://mgmotor.com.np/cars/windsor', 'MG Motor Nepal',
   '/vehicles/mg-windsor.webp', 'Crossover utility vehicle', '2026-07-27'),
  ('byd-dolphin', 'BYD', 'Dolphin', '44.9 kWh', 4115000, 44.9, 340, 'WLTP', 5, null, 60,
   array['Biratnagar','Kathmandu Valley','Pokhara','Bharatpur','Butwal'], 10, 'Incomplete', 7, 'active',
   'https://cimex.com.np/price-list', 'Cimex / BYD Nepal', null, 'Hatchback', '2026-07-27'),
  ('byd-atto-3-advance', 'BYD', 'ATTO 3', 'Advance', 6199000, 49.9, 345, 'WLTP', 5, 175, 70,
   array['Biratnagar','Kathmandu Valley','Pokhara','Bharatpur','Butwal'], 10, 'Needs review', 7, 'active',
   'https://cimex.com.np/price-list', 'Cimex / BYD Nepal', null, 'Compact SUV', '2026-07-27'),
  ('byd-m6', 'BYD', 'M6', 'Standard range', 5890000, 55.4, 420, 'NEDC', 7, null, 89,
   array['Biratnagar','Kathmandu Valley','Pokhara','Bharatpur','Butwal'], 10, 'Needs review', 6, 'active',
   'https://cimex.com.np/price-list', 'Cimex / BYD Nepal', null, 'Electric MPV', '2026-07-27'),
  ('hyundai-creta-electric', 'Hyundai', 'Creta Electric', 'Executive 99 kW', 5196000, 42, 390, 'ARAI', 5, 190, null,
   array['Biratnagar','Kathmandu Valley','Pokhara','Bharatpur','Butwal'], 14, 'Needs review', 7, 'active',
   'https://laxmihyundai.com/price-list', 'Hyundai Nepal', null, 'Compact SUV', '2026-07-27'),
  ('hyundai-kona-gl', 'Hyundai', 'KONA Electric', 'GL 100 kW', 5996000, 39.2, 305, 'WLTP', 5, null, 50,
   array['Biratnagar','Kathmandu Valley','Pokhara','Bharatpur','Butwal'], 14, 'Needs review', 7, 'active',
   'https://laxmihyundai.com/price-list', 'Hyundai Nepal', null, 'Compact SUV', '2026-07-27'),
  ('hyundai-ioniq-5', 'Hyundai', 'IONIQ 5', 'GLS Vision Roof', 10396000, 58, 384, 'WLTP', 5, 160, 350,
   array['Kathmandu Valley','Pokhara'], 14, 'Needs review', 7, 'active',
   'https://laxmihyundai.com/price-list', 'Hyundai Nepal', null, 'Electric crossover', '2026-07-27'),
  ('leapmotor-t03', 'Leapmotor', 'T03', 'Nepal-market variant', 3400000, 37.3, 395, 'NEDC', 4, null, 48,
   array['Kathmandu Valley'], 1, 'Needs review', 7, 'active',
   'https://www.leapmotornepal.com/', 'Leapmotor Nepal',
   '/vehicles/leapmotor-t03.jpg', 'City hatchback', '2026-07-27'),
  ('leapmotor-b10', 'Leapmotor', 'B10', 'Top variant', 5499999, 67.1, 510, 'CLTC', 5, null, null,
   array['Kathmandu Valley'], 1, 'Needs review', 6, 'active',
   'https://www.leapmotornepal.com/', 'Leapmotor Nepal',
   '/vehicles/leapmotor-b10.png', 'Compact SUV', '2026-07-27'),
  ('leapmotor-c10', 'Leapmotor', 'C10', 'Nepal-market variant', 7200000, 69.9, 420, 'WLTP', 5, null, 84,
   array['Kathmandu Valley'], 1, 'Needs review', 7, 'active',
   'https://www.leapmotornepal.com/', 'Leapmotor Nepal',
   '/vehicles/leapmotor-c10.jpg', 'Mid-size SUV', '2026-07-27'),
  ('omoda-e5-pro', 'Omoda', 'E5 Pro', 'FWD', 5159000, 61, 430, 'WLTP', 5, 180, 80,
   array['Kathmandu Valley'], 1, 'Needs review', 7, 'active',
   'https://omodajaecoonepal.com/price', 'Omoda & Jaecoo Nepal',
   '/vehicles/omoda-e5.png', 'Compact SUV', '2026-07-27'),
  ('jaecoo-j5', 'Jaecoo', 'J5 EV', 'FWD', 5699000, 60.9, 461, 'NEDC', 5, null, null,
   array['Kathmandu Valley'], 1, 'Needs review', 6, 'active',
   'https://omodajaecoonepal.com/price', 'Omoda & Jaecoo Nepal',
   '/vehicles/jaecoo-j5.png', 'Compact SUV', '2026-07-27'),
  ('jaecoo-j6t', 'Jaecoo', 'J6T', 'FWD', 6999000, 65.7, 426, 'NEDC', 5, 195, null,
   array['Kathmandu Valley'], 1, 'Needs review', 6, 'active',
   'https://omodajaecoonepal.com/price', 'Omoda & Jaecoo Nepal',
   '/vehicles/jaecoo-j6t.png', 'Electric SUV', '2026-07-27')
on conflict (id) do update set
  brand=excluded.brand, model=excluded.model, variant=excluded.variant, price=excluded.price,
  battery=excluded.battery, range=excluded.range, range_standard=excluded.range_standard,
  seats=excluded.seats, clearance=excluded.clearance, dc=excluded.dc,
  service_cities=excluded.service_cities, service_count=excluded.service_count,
  qa=excluded.qa, evidence=excluded.evidence, status=excluded.status,
  source_url=excluded.source_url, source_label=excluded.source_label,
  image_url=excluded.image_url, body_type=excluded.body_type, verified_at=excluded.verified_at,
  updated_at=now();
